import { createApp } from 'vue'
import App from './App.vue'
import router from './router'

import './styles/fonts.css'
import './styles/styles.css'
import './styles/portfolio-shared.css'
import './styles/header.css'
import './styles/footer.css'
import './styles/collection-card.css'
import './styles/collection-page.css'
import './styles/collection-gallery.css'
import './styles/portfolio-slider.css'
import './styles/category-slider.css'
import './styles/portfolio.css'
import './styles/AdminSlides.css'
createApp(App).use(router).mount('#app')